[package]
name = "frontend"
version = "0.1.0"
description = "Ratatui frontend for my WikiRacer"
authors = ["Walentalien <voliinyk@student.agh.edu.pl>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
